### ISSUE TITLE
cerealConfig.cmake is not insalled

### ISSUE THREAD

**Issue by joaander** [conda-forge/cereal-feedstock#1]
*cereal* should be installed using `CMake` so that `cerealConfig.cmake` is correctly generated and installed. Downstream packages that build with `CMake` expect `find_packcage(cereal)` to work correctly.

e.g. `build.sh` should be
```
mkdir build
cd build
cmake ../ -DJUST_INSTALL_CEREAL=on -CMAKE_INSTALL_PREFIX=${PREFIX}
make install
```

**Comment by saraedum** [comment]
Sure. You mind creating a PR for this?
